discord:
  token: ${DISCORD_OSRSPAL_TOKEN}

osrs:
  base-url: https://secure.runescape.com
  ge-mapping-base-url: https://static.runelite.net/cache/item/names.json

logging:
  level:
    com.rb.osrspal: DEBUG
